package edu.utc.atc.components;
/**
 * Describes how the layout of the different tabSheets looks 
 * Does not contain implementation details so that the Vaadin editor 
 * can be used to make adjustments
 * 
 */
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;

public class TabComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	protected TabSheet tabSheet_MainTab;
	@AutoGenerated
	protected TabSheet tabSheet_Tab2;
	@AutoGenerated
	protected TabSheet tabSheet_Tab1;
	/**
	 * 
	 */
	private static final long serialVersionUID = -7431345916437490687L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 */
	public TabComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_MainTab
		tabSheet_MainTab = buildTabSheet_MainTab();
		mainLayout.addComponent(tabSheet_MainTab, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}


	@AutoGenerated
	private TabSheet buildTabSheet_MainTab() {
		// common part: create layout
		tabSheet_MainTab = new TabSheet();
		//tabSheet_MainTab.setImmediate(true);
		tabSheet_MainTab.setWidth("100.0%");
		tabSheet_MainTab.setHeight("100.0%");
		
		// tabSheet_Tab1
		tabSheet_Tab1 = new TabSheet();
		//tabSheet_Tab1.setImmediate(false);
		tabSheet_Tab1.setWidth("100.0%");
		tabSheet_Tab1.setHeight("100.0%");
		tabSheet_MainTab.addTab(tabSheet_Tab1, "USGS Query", null);
		
		// tabSheet_Tab2
		tabSheet_Tab2 = new TabSheet();
		//tabSheet_Tab2.setImmediate(false);
		tabSheet_Tab2.setWidth("100.0%");
		tabSheet_Tab2.setHeight("100.0%");
		tabSheet_MainTab.addTab(tabSheet_Tab2, "Arrival Time Calculator", null);

		
		return tabSheet_MainTab;
	}

}
