package edu.utc.atc.components;

/**
 * @version 1.0 
 * 
 * @author Jacob D. Coleman
 * Describes how the TimeCalcView looks and its general layout
 * Does not contain implementation details so that the Vaadin editor 
 * can be used to make adjustments
 * 
 */

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.v7.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.v7.ui.PopupDateField;
import com.vaadin.v7.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;

@SuppressWarnings("deprecation")
public class TimeCalcComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	protected HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	protected VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	protected ChartComponent chartComponent_1;
	@AutoGenerated
	protected Table resultsTable;
	@AutoGenerated
	protected VerticalLayout verticalLayout_1;
	@AutoGenerated
	protected Button submitButton;
	@AutoGenerated
	protected ComboBox modelBox;
	@AutoGenerated
	protected TextField depthField;
	@AutoGenerated
	protected TextField distanceField;
	@AutoGenerated
	protected TextField lonField;
	@AutoGenerated
	protected TextField latField;
	@AutoGenerated
	protected PopupDateField popupDateField_1;
	/**
	 * 
	 */
	private static final long serialVersionUID = 2779689616383853031L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TimeCalcComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void addComponent(Button button) {
		// TODO Auto-generated method stub
		
	}

	public void addComponent(Label label) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("109.7%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		mainLayout.addComponent(horizontalSplitPanel_1,
				"top:0.0px;right:0.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		//horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		horizontalSplitPanel_1.addComponent(verticalLayout_1);
		
		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		horizontalSplitPanel_1.addComponent(verticalSplitPanel_1);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		//verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		verticalLayout_1.setSpacing(true);
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setCaption("Time of earthquake");
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("-1px");
		popupDateField_1.setHeight("-1px");
		verticalLayout_1.addComponent(popupDateField_1);
		
		// latField
		latField = new TextField();
		latField.setCaption("Selected earthquake coordinates");
		//latField.setImmediate(false);
		latField.setWidth("100.0%");
		latField.setHeight("-1px");
		verticalLayout_1.addComponent(latField);
		
		// lonField
		lonField = new TextField();
		//lonField.setImmediate(false);
		lonField.setWidth("100.0%");
		lonField.setHeight("-1px");
		verticalLayout_1.addComponent(lonField);
		
		// distanceField
		distanceField = new TextField();
		distanceField.setCaption("Distance in degrees");
		//distanceField.setImmediate(false);
		distanceField.setWidth("100.0%");
		distanceField.setHeight("-1px");
		distanceField.setPlaceholder("Distance");
		verticalLayout_1.addComponent(distanceField);
		
		// depthField
		depthField = new TextField();
		depthField.setCaption("Depth of earthquake");
		//depthField.setImmediate(false);
		depthField.setWidth("100.0%");
		depthField.setHeight("-1px");
		depthField.setPlaceholder("Depth");
		verticalLayout_1.addComponent(depthField);
		
		// modelBox
		modelBox = new ComboBox();
		modelBox.setCaption("Earth Model");
		//modelBox.setImmediate(false);
		modelBox.setWidth("100.0%");
		modelBox.setHeight("24px");
		verticalLayout_1.addComponent(modelBox);
		
		// submitButton
		submitButton = new Button();
		submitButton.setCaption("Submit");
		//submitButton.setImmediate(true);
		submitButton.setWidth("-1px");
		submitButton.setHeight("-1px");
		verticalLayout_1.addComponent(submitButton);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		//verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("100.0%");
		verticalSplitPanel_1.setHeight("100.0%");
		
		// resultsTable
		resultsTable = new Table();
		resultsTable.setImmediate(false);
		resultsTable.setWidth("100.0%");
		resultsTable.setHeight("-1px");
		verticalSplitPanel_1.addComponent(resultsTable);
		
		// chartComponent_1
		chartComponent_1 = new ChartComponent();
		//chartComponent_1.setImmediate(false);
		chartComponent_1.setWidth("100.0%");
		chartComponent_1.setHeight("-1px");
		verticalSplitPanel_1.addComponent(chartComponent_1);
		
		return verticalSplitPanel_1;
	}
	
}
