package edu.utc.atc.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;

import edu.utc.atc.components.NumberBoxCheckComponent;
import edu.utc.atc.components.QueryComponent;

public class QueryView extends QueryComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7581919752425898971L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public QueryView() {
		horizontalSplitPanel_1.setMaxSplitPosition(275, UNITS_PIXELS);
		horizontalSplitPanel_1.setMinSplitPosition(250, UNITS_PIXELS);
		
		submitButton.addClickListener(new Button.ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				
				boolean isValidLong;
				boolean isValidLat;
				boolean isValidMax;
				
				NumberBoxCheckComponent nbc; 
				isValidLong =  new NumberBoxCheckComponent(longField.getValue(), -180, 180, "not within Paramaters", "Plese enter a Longitude", "Not a number").getIsValid();
				isValidLat =  new NumberBoxCheckComponent(latField.getValue(), -180, 180, "not within Paramaters", "Plese enter a Latitude", "Not a number").getIsValid();
				isValidMax =  new NumberBoxCheckComponent(maxMagField.getValue(), -180, 180, "not within Paramaters", "Plese enter a Latitude", "Not a number").getIsValid();

				if(isValidLong == true && isValidLat == true && isValidMax == true)
				{
					
				}
			}
			
		});
	}

}
