package edu.utc.atc.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class QueryComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	protected AbsoluteLayout mainLayout;
	@AutoGenerated
	protected HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	protected Table quakeTable;
	@AutoGenerated
	protected VerticalLayout verticalLayout_1;
	@AutoGenerated
	protected Button submitButton;
	@AutoGenerated
	protected TextField minMagField;
	@AutoGenerated
	protected Label minmagLabel;
	@AutoGenerated
	protected TextField radiusField;
	@AutoGenerated
	protected Label radialLabel;
	@AutoGenerated
	protected TextField longField;
	@AutoGenerated
	protected TextField latField;
	@AutoGenerated
	protected Label coordinateLabel;
	@AutoGenerated
	protected InlineDateField inlineDateField_2;
	/**
	 * 
	 */
	private static final long serialVersionUID = 8913196389988079007L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public QueryComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		mainLayout.addComponent(horizontalSplitPanel_1,
				"top:0.0px;right:0.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		horizontalSplitPanel_1.addComponent(verticalLayout_1);
		
		// quakeTable
		quakeTable = new Table();
		quakeTable.setImmediate(false);
		quakeTable.setWidth("-1px");
		quakeTable.setHeight("-1px");
		horizontalSplitPanel_1.addComponent(quakeTable);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		verticalLayout_1.setSpacing(true);
		
		// inlineDateField_2
		inlineDateField_2 = new InlineDateField();
		inlineDateField_2.setImmediate(false);
		inlineDateField_2.setWidth("100.0%");
		inlineDateField_2.setHeight("100.46%");
		verticalLayout_1.addComponent(inlineDateField_2);
		verticalLayout_1.setExpandRatio(inlineDateField_2, 1.0f);
		
		// coordinateLabel
		coordinateLabel = new Label();
		coordinateLabel.setEnabled(false);
		coordinateLabel.setImmediate(false);
		coordinateLabel.setVisible(false);
		coordinateLabel.setWidth("-1px");
		coordinateLabel.setHeight("15px");
		coordinateLabel.setValue("Station coordinates in degrees");
		verticalLayout_1.addComponent(coordinateLabel);
		
		// latField
		latField = new TextField();
		latField.setCaption("Station coordinates in degrees");
		latField.setImmediate(false);
		latField.setWidth("-1px");
		latField.setHeight("-1px");
		latField.setInputPrompt("Latitude");
		verticalLayout_1.addComponent(latField);
		
		// longField
		longField = new TextField();
		longField.setImmediate(false);
		longField.setWidth("-1px");
		longField.setHeight("-1px");
		longField.setInputPrompt("Longitude");
		verticalLayout_1.addComponent(longField);
		
		// radialLabel
		radialLabel = new Label();
		radialLabel.setEnabled(false);
		radialLabel.setImmediate(false);
		radialLabel.setVisible(false);
		radialLabel.setWidth("-1px");
		radialLabel.setHeight("15px");
		radialLabel.setValue("Distance of interest in degrees");
		verticalLayout_1.addComponent(radialLabel);
		
		// radiusField
		radiusField = new TextField();
		radiusField.setCaption("Distance of interest in degrees");
		radiusField.setImmediate(false);
		radiusField.setWidth("-1px");
		radiusField.setHeight("-1px");
		radiusField.setInputPrompt("Radius");
		verticalLayout_1.addComponent(radiusField);
		
		// minmagLabel
		minmagLabel = new Label();
		minmagLabel.setEnabled(false);
		minmagLabel.setImmediate(false);
		minmagLabel.setVisible(false);
		minmagLabel.setWidth("-1px");
		minmagLabel.setHeight("15px");
		minmagLabel.setValue("Minimum earthquake magnitude");
		verticalLayout_1.addComponent(minmagLabel);
		
		// minMagField
		minMagField = new TextField();
		minMagField.setCaption("Minimum earthquake magnitude");
		minMagField.setImmediate(false);
		minMagField.setWidth("-1px");
		minMagField.setHeight("-1px");
		minMagField.setInputPrompt("Magnitude");
		verticalLayout_1.addComponent(minMagField);
		
		// submitButton
		submitButton = new Button();
		submitButton.setCaption("Submit");
		submitButton.setImmediate(true);
		submitButton.setWidth("-1px");
		submitButton.setHeight("-1px");
		verticalLayout_1.addComponent(submitButton);
		
		return verticalLayout_1;
	}

}
