package edu.utc.atc.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;

public class TabComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private TabSheet tabSheet_5;
	@AutoGenerated
	private TabSheet tabSheet_4;
	@AutoGenerated
	protected TabSheet tabSheet_3;
	@AutoGenerated
	private TabSheet tabSheet_2;
	/**
	 * 
	 */
	private static final long serialVersionUID = -7431345916437490687L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TabComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// tabSheet_2
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(false);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("100.0%");
		tabSheet_1.addTab(tabSheet_2, "Tab", null);
		
		// tabSheet_3
		tabSheet_3 = new TabSheet();
		tabSheet_3.setImmediate(false);
		tabSheet_3.setWidth("100.0%");
		tabSheet_3.setHeight("100.0%");
		tabSheet_1.addTab(tabSheet_3, "Arrival Time Calculator", null);
		
		// tabSheet_4
		tabSheet_4 = new TabSheet();
		tabSheet_4.setImmediate(false);
		tabSheet_4.setWidth("100.0%");
		tabSheet_4.setHeight("100.0%");
		tabSheet_1.addTab(tabSheet_4, "Tab", null);
		
		// tabSheet_5
		tabSheet_5 = new TabSheet();
		tabSheet_5.setImmediate(false);
		tabSheet_5.setWidth("100.0%");
		tabSheet_5.setHeight("100.0%");
		tabSheet_1.addTab(tabSheet_5, "Tab", null);
		
		return tabSheet_1;
	}

}
